import type { HubCard } from "@/components/ui/ModuleHubCards";

export const ADMIN_SIDEBAR_CHILDREN = [
  { label: "Overview", href: "/admin", icon: "space_dashboard" },
  { label: "Operational Control", href: "/admin/operations", icon: "monitoring" },
  { label: "Users", href: "/admin/users", icon: "manage_accounts" },
  { label: "Roles & Permissions", href: "/admin/access/roles", icon: "security" },
  { label: "Access Governance", href: "/admin/access", icon: "policy" },
  { label: "Departments", href: "/admin/departments", icon: "corporate_fare" },
  { label: "Positions", href: "/admin/positions", icon: "work" },
  { label: "Portfolios", href: "/admin/portfolios", icon: "folder_special" },
  { label: "Approval Workflows", href: "/admin/workflows", icon: "account_tree" },
  { label: "Workflow Designer", href: "/admin/workflows/designer", icon: "schema" },
  { label: "Workflow Simulation", href: "/admin/workflows/simulate", icon: "science" },
  { label: "Workflow Analytics", href: "/admin/workflows/analytics", icon: "analytics" },
  { label: "Workflow AI Assist", href: "/admin/workflows/ai", icon: "psychology" },
  { label: "System Settings", href: "/admin/settings", icon: "settings" },
  { label: "HR Settings", href: "/settings/hr", icon: "tune" },
  { label: "Governance Configuration", href: "/admin/governance", icon: "account_balance" },
  { label: "Notifications", href: "/admin/notifications", icon: "notifications" },
  { label: "Timesheet Projects", href: "/admin/timesheet-projects", icon: "task_alt" },
  { label: "Holiday Calendar", href: "/admin/calendar", icon: "event_busy" },
  { label: "Payslip Upload", href: "/admin/payslips", icon: "upload_file" },
  { label: "Salary Assignments", href: "/admin/salary-assignments", icon: "badge" },
  { label: "Platform Audit Trail", href: "/admin/audit-trail", icon: "policy" },
  { label: "Document Register", href: "/admin/documents", icon: "folder_managed" },
  { label: "Ledger Verification", href: "/admin/ledger", icon: "verified_user" },
  { label: "Data Scope & RLS", href: "/admin/data-scope", icon: "database" },
  { label: "Weekly Summary", href: "/admin/weekly-summary", icon: "calendar_month" },
  { label: "Correspondence Settings", href: "/admin/correspondence", icon: "mark_email_read" },
] as const;

export const ADMIN_HUB_CARDS: HubCard[] = [
  { href: "/admin/operations", title: "Operational control", purpose: "Health, modules, flags, jobs, and break-glass.", icon: "monitoring", section: "queues" },
  { href: "/admin/users", title: "Users", purpose: "Accounts, roles, and invitations.", icon: "manage_accounts", section: "queues" },
  { href: "/admin/access", title: "Access governance", purpose: "Reviews, simulator, and explorer.", icon: "policy", section: "queues" },
  { href: "/admin/access/roles", title: "Roles & permissions", purpose: "Role catalogue and permission maps.", icon: "security", section: "queues" },
  { href: "/admin/departments", title: "Departments", purpose: "Organisational structure.", icon: "corporate_fare", section: "views" },
  { href: "/admin/positions", title: "Positions", purpose: "Establishment positions and grades.", icon: "work", section: "views" },
  { href: "/admin/portfolios", title: "Portfolios", purpose: "Programme portfolios.", icon: "folder_special", section: "views" },
  { href: "/admin/workflows", title: "Approval workflows", purpose: "Module approval chains.", icon: "account_tree", section: "views" },
  { href: "/admin/notifications", title: "Notifications", purpose: "Broadcasts and ack campaigns.", icon: "notifications", section: "views" },
  { href: "/admin/calendar", title: "Holiday calendar", purpose: "Public holidays used by leave and payroll.", icon: "event_busy", section: "views" },
  { href: "/admin/payslips", title: "Payslip upload", purpose: "Bulk payslip ingest.", icon: "upload_file", section: "views" },
  { href: "/admin/salary-assignments", title: "Salary assignments", purpose: "Confirmed net salary links.", icon: "badge", section: "views" },
  { href: "/admin/audit-trail", title: "Platform audit trail", purpose: "Searchable platform events.", icon: "policy", section: "views" },
  { href: "/admin/documents", title: "Document register", purpose: "Retention and backup status.", icon: "folder_managed", section: "views" },
  { href: "/admin/ledger", title: "Ledger verification", purpose: "Integrity checks on the ledger.", icon: "verified_user", section: "views" },
  { href: "/admin/weekly-summary", title: "Weekly summary", purpose: "Admin weekly-summary settings.", icon: "calendar_month", section: "views" },
  { href: "/admin/governance", title: "Governance configuration", purpose: "Data policies and institution-wide settings.", icon: "account_balance", section: "tools" },
  { href: "/admin/correspondence", title: "Correspondence settings", purpose: "File codes, signatories, and reference rules.", icon: "mark_email_read", section: "tools" },
  { href: "/admin/workflows/designer", title: "Workflow designer", purpose: "Visual workflow editor.", icon: "schema", section: "tools" },
  { href: "/admin/workflows/simulate", title: "Workflow simulation", purpose: "Dry-run a workflow.", icon: "science", section: "tools" },
  { href: "/admin/workflows/analytics", title: "Workflow analytics", purpose: "Step duration and bottlenecks.", icon: "analytics", section: "tools" },
  { href: "/admin/workflows/ai", title: "Workflow AI assist", purpose: "Drafting support. Never auto-approves.", icon: "psychology", section: "tools" },
  { href: "/admin/settings", title: "System settings", purpose: "Organisation and platform settings.", icon: "settings", section: "tools" },
  { href: "/settings/hr", title: "HR settings", purpose: "Leave types and HR policy.", icon: "tune", section: "tools" },
  { href: "/admin/timesheet-projects", title: "Timesheet projects", purpose: "Projects staff can charge time to.", icon: "task_alt", section: "tools" },
  { href: "/admin/data-scope", title: "Data scope & RLS", purpose: "Row-level access diagnostics.", icon: "database", section: "tools" },
];
