import 'dart:async';

import 'package:dio/dio.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../firebase_options.dart';
import '../auth/auth_providers.dart';

/// Background message handler — must be a top-level function.
@pragma('vm:entry-point')
Future<void> _firebaseBackgroundHandler(RemoteMessage message) async {
  // Background messages are handled by the OS notification tray.
  // No UI work needed here.
}

/// Service that initialises Firebase Messaging, requests permissions,
/// registers the FCM token with the backend, and exposes a stream of
/// foreground messages for the in-app banner.
class FcmService {
  FcmService({required Dio dio}) : _dio = dio;

  final Dio _dio;
  bool _initialised = false;

  final _foregroundMessageController =
      StreamController<RemoteMessage>.broadcast();

  /// Stream of messages received while the app is in the foreground.
  Stream<RemoteMessage> get foregroundMessages =>
      _foregroundMessageController.stream;

  /// Initialise Firebase and set up listeners.
  /// Safe to call multiple times — will no-op after first successful init.
  Future<void> init() async {
    if (_initialised) return;

    try {
      // Firebase.initializeApp() requires firebase_options.dart generated by
      // `flutterfire configure`. If that file doesn't exist yet, this throws
      // and we fall through to the catch block — the app continues without FCM.
      if (Firebase.apps.isEmpty) {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
      }

      final messaging = FirebaseMessaging.instance;

      // Request permission (iOS/web; Android 13+ also requires this).
      final settings = await messaging.requestPermission(
        alert: true,
        badge: true,
        sound: true,
        provisional: false,
      );

      if (settings.authorizationStatus == AuthorizationStatus.authorized ||
          settings.authorizationStatus == AuthorizationStatus.provisional) {
        // Register background handler.
        FirebaseMessaging.onBackgroundMessage(_firebaseBackgroundHandler);

        // Forward foreground messages to the banner stream.
        FirebaseMessaging.onMessage.listen((message) {
          _foregroundMessageController.add(message);
        });

        // Register token with backend.
        await _registerToken(messaging);

        // Re-register whenever the token rotates.
        messaging.onTokenRefresh.listen((token) {
          _uploadToken(token);
        });
      }

      _initialised = true;
    } catch (e) {
      // Firebase not configured yet — app continues normally without push.
      if (kDebugMode) {
        debugPrint(
          '[FcmService] Firebase not initialised ($e). '
          'Run `flutterfire configure` to enable push notifications.',
        );
      }
    }
  }

  /// Remove the token from the backend on logout.
  Future<void> unregister() async {
    try {
      final messaging = FirebaseMessaging.instance;
      final token = await messaging.getToken();
      if (token != null) {
        await _dio.delete('/auth/device-token', data: {'token': token});
        await messaging.deleteToken();
      }
    } catch (_) {}
  }

  Future<void> _registerToken(FirebaseMessaging messaging) async {
    try {
      String? token;
      if (kIsWeb) {
        // Web push requires a VAPID key from the Firebase console.
        // token = await messaging.getToken(vapidKey: 'YOUR_VAPID_KEY');
      } else {
        token = await messaging.getToken();
      }
      if (token != null) {
        await _uploadToken(token);
      }
    } catch (e) {
      if (kDebugMode) debugPrint('[FcmService] Token registration failed: $e');
    }
  }

  Future<void> _uploadToken(String token) async {
    try {
      String platform = 'android';
      if (kIsWeb) {
        platform = 'web';
      } else if (defaultTargetPlatform == TargetPlatform.iOS ||
          defaultTargetPlatform == TargetPlatform.macOS) {
        platform = 'ios';
      }

      await _dio.post('/auth/device-token', data: {
        'token': token,
        'platform': platform,
        'device_name': _deviceLabel(),
      });
    } catch (e) {
      if (kDebugMode) debugPrint('[FcmService] Token upload failed: $e');
    }
  }

  String _deviceLabel() {
    if (kIsWeb) return 'Web browser';
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return 'Android device';
      case TargetPlatform.iOS:
        return 'iPhone';
      default:
        return 'Mobile device';
    }
  }

  void dispose() {
    _foregroundMessageController.close();
  }
}

// ---------------------------------------------------------------------------
// Riverpod provider
// ---------------------------------------------------------------------------

final fcmServiceProvider = Provider<FcmService>((ref) {
  final client = ref.watch(apiClientProvider);
  final service = FcmService(dio: client.dio);
  ref.onDispose(service.dispose);
  return service;
});
