<?php

namespace App\Modules\Assets\Export;

use App\Modules\Assets\Reporting\SpreadsheetSafety;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Worksheet\Table;
use PhpOffice\PhpSpreadsheet\Worksheet\Table\TableStyle;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

final class AssetReportWorkbook
{
    /**
     * @param  array<string, mixed>  $payload
     */
    public function __construct(private readonly array $payload) {}

    public function stream(string $output): void
    {
        $spreadsheet = $this->build();
        (new Xlsx($spreadsheet))->save($output);
        $spreadsheet->disconnectWorksheets();
    }

    public function write(string $path): void
    {
        $spreadsheet = $this->build();
        (new Xlsx($spreadsheet))->save($path);
        $spreadsheet->disconnectWorksheets();
    }

    public function build(): Spreadsheet
    {
        $spreadsheet = new Spreadsheet;
        $this->writeInfo($spreadsheet);
        $this->writeSummary($spreadsheet);
        $this->writeData($spreadsheet);
        $spreadsheet->setActiveSheetIndex(0);

        return $spreadsheet;
    }

    private function writeInfo(Spreadsheet $spreadsheet): void
    {
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Report Info');
        $run = $this->payload['run'] ?? [];
        $rows = [
            ['Title', $this->payload['title'] ?? 'Fixed asset report'],
            ['Report ID', $run['report_id'] ?? ''],
            ['Report run ID', $run['report_run_id'] ?? ''],
            ['Template version', $run['template_version'] ?? ''],
            ['Official', ! empty($run['official']) ? 'Official' : 'Draft'],
            ['Data as of', $run['data_as_of'] ?? ''],
            ['Generated at', $run['generated_at'] ?? ''],
            ['Timezone', 'UTC'],
            ['Generated by', data_get($run, 'generated_by.name')],
            ['Generator email', data_get($run, 'generated_by.email')],
            ['Integrity', $run['checksum'] ?? ''],
        ];
        foreach (($run['parameters'] ?? []) as $key => $value) {
            $rows[] = ['Parameter: '.$key, is_scalar($value) ? (string) $value : json_encode($value)];
        }
        $sheet->fromArray(['Field', 'Value'], null, 'A1');
        $sheet->fromArray($rows, null, 'A2');
        $this->styleHeader($sheet, 'A1:B1');
        $sheet->freezePane('A2');
        $sheet->getColumnDimension('A')->setWidth(28);
        $sheet->getColumnDimension('B')->setWidth(56);
    }

    private function writeSummary(Spreadsheet $spreadsheet): void
    {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Summary');
        $sheet->fromArray(['Measure', 'Value'], null, 'A1');
        $this->styleHeader($sheet, 'A1:B1');
        $row = 2;
        foreach (($this->payload['totals'] ?? []) as $key => $value) {
            $sheet->setCellValue('A'.$row, (string) $key);
            $sheet->setCellValue('B'.$row, is_scalar($value) ? $value : json_encode($value));
            $row++;
        }
        $sheet->freezePane('A2');
        $sheet->getColumnDimension('A')->setWidth(28);
        $sheet->getColumnDimension('B')->setWidth(24);
    }

    private function writeData(Spreadsheet $spreadsheet): void
    {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Data');
        $columns = $this->payload['columns'] ?? [];
        $headers = array_map(fn (array $col) => $col['label'] ?? $col['key'], $columns);
        if ($headers === []) {
            $headers = array_keys($this->payload['data'][0] ?? ['empty' => null]);
            $columns = array_map(fn (string $key) => ['key' => $key, 'type' => 'text'], $headers);
        }
        $sheet->fromArray($headers, null, 'A1');
        $this->styleHeader($sheet, 'A1:'.$sheet->getHighestColumn().'1');
        $sheet->freezePane('A2');

        $r = 2;
        foreach ($this->payload['data'] ?? [] as $item) {
            $c = 1;
            foreach ($columns as $column) {
                $key = $column['key'];
                $type = $column['type'] ?? 'text';
                $value = is_array($item) ? ($item[$key] ?? null) : null;
                $coord = $sheet->getCell([$c, $r])->getCoordinate();
                if ($type === 'number' && is_numeric($value)) {
                    $sheet->setCellValue($coord, (float) $value);
                    $sheet->getStyle($coord)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
                } elseif ($type === 'date' && is_string($value) && $value !== '') {
                    $sheet->setCellValue($coord, $value);
                    $sheet->getStyle($coord)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_DATE_YYYYMMDD);
                } else {
                    $text = SpreadsheetSafety::formulaSafe($value === null ? '' : (string) $value);
                    $sheet->setCellValueExplicit($coord, $text, DataType::TYPE_STRING);
                }
                $c++;
            }
            $r++;
        }

        $lastCol = $sheet->getHighestColumn();
        $lastRow = max(2, $r - 1);
        foreach (range(1, count($columns)) as $col) {
            $sheet->getColumnDimensionByColumn($col)->setAutoSize(true);
        }

        if (($this->payload['data'] ?? []) !== [] && class_exists(Table::class)) {
            try {
                $table = new Table('A1:'.$lastCol.$lastRow, 'FARData');
                $style = new TableStyle;
                $style->setShowRowStripes(true);
                $table->setStyle($style);
                $sheet->addTable($table);
            } catch (\Throwable) {
                $sheet->setAutoFilter('A1:'.$lastCol.$lastRow);
            }
        } else {
            $sheet->setAutoFilter('A1:'.$lastCol.$lastRow);
        }
    }

    private function styleHeader(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $sheet, string $range): void
    {
        $sheet->getStyle($range)->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['rgb' => '1F4E79'],
            ],
            'alignment' => ['wrapText' => true, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheet->getRowDimension(1)->setRowHeight(22);
    }
}
