<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Timesheet {{ $timesheet->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
        h1 { font-size: 16px; margin: 0 0 6px; }
        .banner { background: #1d85ed; color: #fff; padding: 10px 12px; margin-bottom: 14px; }
        .meta td { padding: 2px 10px 2px 0; vertical-align: top; }
        table.entries { width: 100%; border-collapse: collapse; margin-top: 12px; }
        table.entries th, table.entries td { border: 1px solid #ccc; padding: 4px 6px; text-align: left; }
        table.entries th { background: #f3f3f3; }
        .muted { color: #666; font-size: 10px; margin-top: 14px; }
    </style>
</head>
<body>
    <div class="banner"><strong>SADC PF Nexus — Official Timesheet</strong></div>
    <h1>Week {{ $timesheet->week_start?->toDateString() }} – {{ $timesheet->week_end?->toDateString() }}</h1>
    <table class="meta">
        <tr><td>Employee</td><td>{{ $timesheet->user?->name }}</td></tr>
        <tr><td>Employee #</td><td>{{ $timesheet->user?->employee_number ?? '—' }}</td></tr>
        <tr><td>Position</td><td>{{ $timesheet->user?->job_title ?? '—' }}</td></tr>
        <tr><td>Department</td><td>{{ $timesheet->user?->department?->name ?? '—' }}</td></tr>
        <tr><td>Status</td><td>{{ $timesheet->status }}</td></tr>
        <tr><td>Ordinary hours</td><td>{{ $timesheet->total_hours }}</td></tr>
        <tr><td>Overtime hours</td><td>{{ $timesheet->overtime_hours }}</td></tr>
        <tr><td>Approver</td><td>{{ $timesheet->approver?->name ?? '—' }}</td></tr>
    </table>

    <table class="entries">
        <thead>
            <tr>
                <th>Date</th>
                <th>Hours</th>
                <th>OT</th>
                <th>Project</th>
                <th>Bucket</th>
                <th>Category</th>
                <th>Description</th>
                <th>Source</th>
            </tr>
        </thead>
        <tbody>
            @forelse($timesheet->entries as $entry)
                <tr>
                    <td>{{ $entry->work_date?->toDateString() }}</td>
                    <td>{{ $entry->hours }}</td>
                    <td>{{ $entry->overtime_hours }}</td>
                    <td>{{ $entry->project?->label ?? '—' }}</td>
                    <td>{{ $entry->work_bucket ?? '—' }}</td>
                    <td>{{ $entry->entry_category ?? '—' }}</td>
                    <td>{{ $entry->description }}</td>
                    <td>{{ $entry->source_type }}</td>
                </tr>
            @empty
                <tr><td colspan="8">No entries</td></tr>
            @endforelse
        </tbody>
    </table>

    <p class="muted">
        Generated by {{ $generatedBy->name }} at {{ $generatedAt->toDateTimeString() }}.
        Confidential — internal SADC PF use. Overtime pay XOR TOIL rules are enforced in the OT module; this export does not invent rates.
    </p>
</body>
</html>
