<?php

/** Role templates from PRD §11 — seedable bundles with versioned publish. */
return [
    'General Employee' => [
        'purpose' => 'Self-service access and assigned work',
        'risk_level' => 'low',
        'permissions' => [
            'dashboard.view', 'my_work.view',
            'leave.module.view', 'leave.request.create.self', 'leave.request.read.self',
            'leave.request.edit.created', 'leave.request.submit.created', 'leave.request.withdraw.created',
            'leave.balance.read.self', 'leave.view', 'leave.create',
            'travel.module.view', 'travel.request.create.self', 'travel.request.read.self',
            'travel.create',
            'salary_advance.module.view', 'salary_advance.request.create.self', 'salary_advance.request.read.self',
            'salary_advance.request.edit.created', 'salary_advance.request.submit.created',
            'salary_advance.view', 'salary_advance.create',
            'timesheet.module.view', 'timesheet.create.self', 'timesheet.read.self',
            'timesheets.view', 'timesheets.create', 'timesheets.view-own', 'timesheets.create-own',
            'timesheets.edit-own-draft', 'timesheets.submit',
            'assignment.module.view', 'assignment.read.assigned', 'assignments.view', 'assignments.create',
            'weekly_report.module.view', 'weekly_report.create.self',
            'weekly-reports.view-own', 'weekly-reports.create-own', 'weekly-reports.edit-own-draft', 'weekly-reports.submit',
            'profile.read.self', 'profile.edit.self',
            'notifications.view.own', 'notifications.manage.preferences',
            'notifications.view-own', 'notifications.manage-own-preferences', 'notifications.acknowledge',
            'approvals.inbox.view',
            'documents.upload', 'documents.view.authorised', 'documents.view', 'documents.download', 'documents.sign',
            'imprest.view', 'imprest.create',
            'procurement.create',
            'procurement.request.create', 'procurement.request.read.created',
            'procurement.request.edit.created', 'procurement.request.submit.created',
            'governance.view',
            'decisions.view', 'decisions.create',
            'correspondence.view', 'correspondence.create',
            'calendar.view', 'calendar.create',
            'saam.view', 'saam.delegate',
            'people.view-directory', 'people.view-profile',
            'organisation.view',
            'delegations.create', 'delegations.revoke',
            'signatures.enrol',
            'workflows.view-own', 'workflows.submit', 'workflows.act', 'workflows.withdraw',
            'lifecycle.view-own', 'lifecycle.complete-own-tasks',
            'parliaments.view',
            // Incident report / own timesheet under /hr* — not org HR admin (hr.view).
            'hr.create',
            // Activity reporting is staff self-service; specialised M&E Officer still owns review.
            'mande.view', 'mande.create',
        ],
        'inherits' => [],
        'legacy_roles' => ['staff'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Supervisor / Line Manager' => [
        'purpose' => 'Review direct-report submissions and assignments',
        'risk_level' => 'medium',
        'permissions' => [
            'leave.request.read.direct_reports', 'leave.request.recommend.assigned', 'leave.request.return.assigned',
            'timesheet.approve.assigned', 'assignment.read.assigned', 'weekly_report.review.team',
            'approvals.task.act.assigned',
            'travel.view',
            // Legacy HOD departmental procurement review (HOD maps here, not Director).
            'procurement.view', 'procurement.hod_approve', 'procurement.request.approve.assigned',
            'timesheets.view', 'timesheets.view-team', 'timesheets.review-team', 'timesheets.return', 'timesheets.approve',
            'overtime.recommend', 'overtime.approve',
            'weekly-reports.view-team', 'weekly-reports.review-team', 'weekly-reports.return', 'weekly-reports.accept',
        ],
        'inherits' => ['General Employee'],
        'legacy_roles' => ['HOD'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Head of Department / Director' => [
        'purpose' => 'Departmental oversight and assigned approvals',
        'risk_level' => 'high',
        'permissions' => ['leave.request.authorise.assigned', 'leave.request.reject.assigned', 'leave.calendar.view.department', 'travel.request.approve.assigned', 'procurement.request.approve.assigned', 'salary_advance.approve.assigned', 'programme.manager_review.act.assigned', 'risk.module.view', 'risk.create'],
        'inherits' => ['Supervisor / Line Manager'],
        // HOD remains the supervisor role; only Director maps to this wider
        // directorate scope.
        'legacy_roles' => ['Director'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Secretary General' => [
        'purpose' => 'Final institutional approvals and executive oversight',
        'risk_level' => 'critical',
        'permissions' => [
            'leave.request.authorise.assigned', 'leave.module.view', 'leave.view', 'leave.approve',
            'travel.request.approve.assigned', 'travel.view', 'travel.approve', 'travel.final-approve',
            'salary_advance.approve.assigned', 'salary_advance.view', 'salary_advance.approve',
            'programme.sg_approval.act.assigned',
            'procurement.award.approve.assigned', 'procurement.view', 'procurement.approve', 'procurement.award',
            'approvals.task.act.assigned',
            'admin.roles.approve', 'admin.roles.revoke',
            'reports.view.authorised', 'reports.view', 'reports.export',
            'correspondence.read.confidential',
            'finance.view', 'finance.approve',
            'imprest.view', 'imprest.approve',
            'governance.view', 'governance.approve',
            'decisions.view', 'decisions.create', 'decisions.adopt', 'decisions.manage', 'decisions.admin',
            'hr.view', 'hr.approve',
            'audit.view', 'audit.plan.approve',
        ],
        'inherits' => [],
        'legacy_roles' => ['Secretary General'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'HR and Administration Officer' => [
        'purpose' => 'HR records, leave certification, travel logistics and administration',
        'risk_level' => 'high',
        'permissions' => [
            'leave.module.view', 'leave.balance.certify.assigned', 'leave.balance.read.assigned_staff',
            'leave.calendar.view.organisation', 'leave.report.view', 'leave.balance.export',
            'leave.view',
            'travel.module.view', 'travel.view', 'travel.review-toil', 'travel.prepare-for-others', 'travel.health-view',
            'admin.organisation.manage',
            'users.view',
            'hr.view', 'hr.create', 'hr.edit', 'hr.approve', 'hr.admin',
            'hr_settings.view', 'hr_settings.edit', 'hr_settings.approve', 'hr_settings.publish',
            'timesheets.view', 'timesheets.create', 'timesheets.approve',
            'timesheets.view-team', 'timesheets.review-team', 'timesheets.return',
            'timesheets.manage-schedules', 'timesheets.manage-periods',
            'timesheets.export', 'timesheets.audit', 'timesheets.admin',
            'overtime.request', 'overtime.recommend', 'overtime.approve',
            'overtime.verify-actual', 'overtime.hr-validate', 'overtime.send-toil',
            'appraisals.view', 'appraisals.create', 'appraisals.review', 'appraisals.admin',
            'conduct.view', 'conduct.create', 'conduct.admin',
            'governance.view',
            'reports.view',
            'imprest.view', 'imprest.approve',
            'people.view-directory', 'people.view-profile', 'people.view-confidential', 'people.manage',
            'organisation.view', 'organisation.manage', 'positions.manage', 'reporting-lines.manage',
            'roles.view', 'roles.assign',
            'authorities.manage',
            'acting-appointments.create', 'acting-appointments.approve',
            'delegations.create', 'delegations.approve', 'delegations.revoke',
            'signatures.enrol', 'signatures.verify', 'signatures.administer', 'documents.sign',
            'access-reviews.manage', 'onboarding.manage', 'offboarding.manage',
            'lifecycle.view', 'lifecycle.manage-onboarding', 'lifecycle.manage-separation',
            'lifecycle.complete-own-tasks', 'lifecycle.complete-department-tasks', 'lifecycle.view-confidential',
            'lifecycle.templates.view', 'lifecycle.templates.edit', 'lifecycle.templates.publish',
            'lifecycle.approve-exceptions', 'lifecycle.finalise-separation', 'lifecycle.admin',
            'people.export', 'identity.audit',
            'people.certificate.enrol', 'people.esign.manage', 'people.m365.sync',
            'people.recertification.manage', 'people.sod.analyse', 'people.org-scenarios.manage',
            'people.payroll-link.manage', 'people.signatures.publish-verify',
            'people.succession.manage', 'people.skills.manage', 'people.analytics.view',
            'people.ai.suggest', 'people.ai.apply', 'people.privilege-alerts.manage',
        ],
        'inherits' => [],
        'legacy_roles' => ['HR Manager', 'HR Administrator', 'Administration Officer'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Finance Officer' => [
        'purpose' => 'Financial validation, calculations and processing',
        'risk_level' => 'critical',
        'permissions' => [
            'programme.finance_review.read.assigned', 'programme.finance_review.update.assigned',
            'programme.budget_availability.confirm.assigned', 'programme.module.view',
            'salary_advance.module.view', 'salary_advance.financial_details.read.assigned',
            'salary_advance.salary_verify.assigned', 'salary_advance.outstanding_advance_verify.assigned',
            'salary_advance.threshold_verify.assigned', 'salary_advance.finance_certify.assigned',
            'salary_advance.payroll_deduction.record.assigned',
            'reports.view.authorised', 'reports.export.authorised',
            'finance.view', 'finance.create', 'finance.approve', 'finance.export',
            'salary_advance.view', 'salary_advance.create', 'salary_advance.certify',
            'salary_advance.pay', 'salary_advance.recover', 'salary_advance.export', 'salary_advance.admin',
            'travel.view', 'travel.finance-review', 'travel.export', 'travel.health-view',
            'procurement.view', 'procurement.manage_po', 'procurement.approve_invoice', 'procurement.manage_budget',
            'governance.view', 'audit.view',
            'reports.view', 'reports.export', 'reports.schedule', 'reports.manage-schedules',
            'hr_settings.view', 'hr_settings.edit', 'hr_settings.approve', 'hr_settings.publish',
            'overtime.send-payroll', 'timesheets.export', 'timesheets.view',
            'imprest.view', 'imprest.approve',
        ],
        'inherits' => [],
        'legacy_roles' => ['Finance Controller'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Director Finance and Corporate Services' => [
        'purpose' => 'Assigned financial and corporate approvals',
        'risk_level' => 'critical',
        'permissions' => ['programme.funds_procurement_rates.authorise.assigned', 'salary_advance.approve.assigned', 'travel.request.approve.assigned', 'procurement.purchase_order.create.assigned'],
        'inherits' => ['Finance Officer'],
        // Finance Controller is deliberately mapped to Finance Officer. The
        // director-level approval role is assigned explicitly as its own
        // canonical role and must not be inherited by every controller.
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Programme Officer' => [
        'purpose' => 'Prepare and manage assigned programmes and PIFs',
        'risk_level' => 'medium',
        'permissions' => ['programme.module.view', 'programme.request.create', 'programme.request.read.created', 'programme.request.edit.created', 'programme.request.submit.created', 'programme.document.manage.created', 'programme.conflict_declaration.submit.created', 'programme.mande_link.read.authorised'],
        'inherits' => [],
        // Generic staff must not receive programme-authoring access merely
        // because Programme Officer used to share the staff alias.
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Programme Manager' => [
        'purpose' => 'Programme supervision and assigned programme approvals',
        'risk_level' => 'high',
        'permissions' => ['programme.request.read.assigned', 'programme.manager_review.act.assigned', 'programme.activity_authorise.act.assigned'],
        'inherits' => ['Programme Officer'],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'M&E Officer' => [
        'purpose' => 'Indicator, evidence and activity-report processing',
        'risk_level' => 'medium',
        'permissions' => [
            'mande.module.view', 'mande.indicator.read', 'mande.indicator.create',
            'mande.activity_report.create', 'mande.evidence.upload', 'mande.dashboard.view',
            'mande.view', 'mande.create',
        ],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'M&E Manager' => [
        'purpose' => 'M&E review, acceptance, closure and reporting',
        'risk_level' => 'high',
        'permissions' => [
            'mande.activity_report.review.assigned', 'mande.activity_report.accept.assigned',
            'mande.evidence.validate.assigned', 'mande.configuration.manage', 'mande.strategic_plan.manage',
            'mande.review', 'mande.admin',
        ],
        'inherits' => ['M&E Officer'],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Procurement Officer' => [
        'purpose' => 'Procurement administration and controlled process execution',
        'risk_level' => 'high',
        'permissions' => [
            'procurement.module.view', 'procurement.request.create', 'procurement.request.read.created',
            'procurement.request.read.assigned', 'procurement.request.edit.created',
            'procurement.request.submit.created', 'procurement.request.review.assigned',
            'procurement.rfq.publish.assigned', 'procurement.supplier.read', 'procurement.supplier.approve',
            'procurement.purchase_order.create.assigned', 'procurement.report.view',
            'procurement.view', 'procurement.create', 'procurement.approve', 'procurement.admin',
            'procurement.award', 'procurement.manage_vendors', 'procurement.manage_po', 'procurement.receive_goods',
            'assets.view', 'assets.create', 'finance.view', 'governance.view',
            'stock.view', 'stock.create', 'stock.edit', 'stock.issue', 'stock.manage', 'stock.approve', 'stock.transfer',
        ],
        'inherits' => [],
        'legacy_roles' => ['Procurement Officer'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Procurement Evaluation Committee Member' => [
        'purpose' => 'Assigned evaluation only (feature-only)',
        'risk_level' => 'high',
        'permissions' => ['my_work.view', 'procurement.evaluation.read.assigned', 'procurement.evaluation.score.assigned', 'procurement.evaluation.submit.assigned'],
        'inherits' => [],
        'legacy_roles' => ['Committee Member'],
        'feature_only' => true,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Internal Auditor' => [
        'purpose' => 'Read-only assurance access to authorised records and audit data',
        'risk_level' => 'high',
        'permissions' => [
            'audit.event.read.organisation', 'audit.admin', 'audit.view', 'audit.export',
            'audit.universe.manage', 'audit.plan.manage', 'audit.engagement.manage', 'audit.engagement.fieldwork',
            'audit.findings.issue', 'audit.findings.view', 'audit.workpapers.manage', 'audit.workpapers.review',
            'audit.report.draft', 'audit.report.issue', 'audit.corrective.verify',
            'audit.external.coordinate', 'audit.dashboard.auditor', 'audit.settings.view',
            'audit.events.view', 'audit.confidential.view',
            'leave.module.view', 'leave.view', 'leave.report.view',
            'procurement.report.view', 'procurement.view',
            'programme.report.view', 'salary_advance.report.view',
            'reports.view.authorised', 'reports.view',
            'risk.module.view', 'risk.view', 'risk.review',
            'mande.module.view', 'mande.view', 'mande.review',
            'finance.view', 'travel.view', 'imprest.view', 'hr.view', 'governance.view',
        ],
        'inherits' => [],
        'legacy_roles' => ['Internal Auditor'],
        'feature_only' => false,
        'read_only' => true,
        'no_business_approve' => false,
    ],
    'External Auditor' => [
        'purpose' => 'Time-limited, engagement-scoped read-only assurance access',
        'risk_level' => 'high',
        'permissions' => ['audit.event.read.organisation', 'reports.view.authorised', 'finance.view', 'risk.module.view', 'mande.module.view'],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => true,
        'no_business_approve' => true,
    ],
    'ICT Platform Administrator' => [
        'purpose' => 'Technical platform administration without automatic business-data access',
        'risk_level' => 'critical',
        'permissions' => ['admin.platform.manage', 'admin.users.view', 'admin.users.create', 'admin.users.edit', 'dashboard.view', 'notifications.view.own', 'profile.read.self'],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => true,
    ],
    'Security and Access Administrator' => [
        'purpose' => 'Role and access administration without business approval authority',
        'risk_level' => 'critical',
        'permissions' => ['admin.roles.view', 'admin.roles.manage', 'admin.roles.assign', 'admin.access.simulate', 'admin.access.explore', 'admin.access.requests.manage', 'admin.access.reviews.manage', 'admin.security.manage', 'admin.users.view'],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => true,
    ],
    'Workflow Administrator' => [
        'purpose' => 'Workflow configuration and operational correction under controlled conditions',
        'risk_level' => 'high',
        'permissions' => ['admin.workflow.configure', 'approvals.inbox.view'],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => true,
    ],
    'External Supplier' => [
        'purpose' => 'Supplier portal and own procurement interactions',
        'risk_level' => 'medium',
        'permissions' => ['procurement.bid.submit.own', 'procurement.bid.read.own', 'supplier.portal'],
        'inherits' => [],
        'legacy_roles' => ['Supplier', 'Supplier Finance User'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
];
