<?php

/** Role templates from PRD §11 — seedable bundles with versioned publish. */
return [
    'General Employee' => [
        'purpose' => 'Self-service access and assigned work',
        'risk_level' => 'low',
        'permissions' => ['dashboard.view', 'my_work.view', 'leave.module.view', 'leave.request.create.self', 'leave.request.read.self', 'leave.request.edit.created', 'leave.request.submit.created', 'leave.request.withdraw.created', 'leave.balance.read.self', 'travel.module.view', 'travel.request.create.self', 'travel.request.read.self', 'salary_advance.module.view', 'salary_advance.request.create.self', 'salary_advance.request.read.self', 'salary_advance.request.edit.created', 'salary_advance.request.submit.created', 'timesheet.module.view', 'timesheet.create.self', 'timesheet.read.self', 'assignment.module.view', 'assignment.read.assigned', 'weekly_report.module.view', 'weekly_report.create.self', 'profile.read.self', 'profile.edit.self', 'notifications.view.own', 'notifications.manage.preferences', 'approvals.inbox.view', 'documents.upload', 'documents.view.authorised'],
        'inherits' => [],
        'legacy_roles' => ['staff'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Supervisor / Line Manager' => [
        'purpose' => 'Review direct-report submissions and assignments',
        'risk_level' => 'medium',
        'permissions' => ['leave.request.read.direct_reports', 'leave.request.recommend.assigned', 'leave.request.return.assigned', 'timesheet.approve.assigned', 'assignment.read.assigned', 'weekly_report.review.team', 'approvals.task.act.assigned'],
        'inherits' => ['General Employee'],
        'legacy_roles' => ['HOD'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Head of Department / Director' => [
        'purpose' => 'Departmental oversight and assigned approvals',
        'risk_level' => 'high',
        'permissions' => ['leave.request.authorise.assigned', 'leave.request.reject.assigned', 'leave.calendar.view.department', 'travel.request.approve.assigned', 'procurement.request.approve.assigned', 'salary_advance.approve.assigned', 'programme.manager_review.act.assigned', 'risk.module.view', 'risk.create'],
        'inherits' => ['Supervisor / Line Manager'],
        // HOD remains the supervisor role; only Director maps to this wider
        // directorate scope.
        'legacy_roles' => ['Director'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Secretary General' => [
        'purpose' => 'Final institutional approvals and executive oversight',
        'risk_level' => 'critical',
        'permissions' => ['dashboard.view', 'leave.request.authorise.assigned', 'travel.request.approve.assigned', 'salary_advance.approve.assigned', 'programme.sg_approval.act.assigned', 'procurement.award.approve.assigned', 'approvals.task.act.assigned', 'admin.roles.approve', 'admin.roles.revoke', 'reports.view.authorised', 'correspondence.read.confidential', 'correspondence.approve', 'correspondence.route', 'audit.plan.approve', 'audit.findings.view'],
        'inherits' => [],
        'legacy_roles' => ['Secretary General'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'HR and Administration Officer' => [
        'purpose' => 'HR records, leave certification, travel logistics and administration',
        'risk_level' => 'high',
        'permissions' => [
            'dashboard.view',
            'leave.module.view',
            'leave.balance.certify.assigned',
            'leave.balance.read.assigned_staff',
            'leave.calendar.view.organisation',
            'leave.report.view',
            'leave.balance.export',
            'travel.module.view',
            'admin.organisation.manage',
            'hr.view',
            'hr.create',
            'hr.edit',
            'hr.admin',
            'timesheets.view',
            'timesheets.create',
            'timesheets.approve',
            'timesheets.admin',
            'timesheets.manage-schedules',
            'timesheets.manage-periods',
        ],
        'inherits' => [],
        'legacy_roles' => ['HR Manager', 'HR Administrator', 'Administration Officer'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Finance Officer' => [
        'purpose' => 'Financial validation, calculations and processing',
        'risk_level' => 'critical',
        'permissions' => [
            'dashboard.view',
            'finance.view',
            'finance.create',
            'finance.approve',
            'finance.export',
            'programme.finance-review',
            'programme.finance_review.read.assigned',
            'programme.finance_review.update.assigned',
            'programme.budget_availability.confirm.assigned',
            'programme.module.view',
            'salary_advance.module.view',
            'salary_advance.financial_details.read.assigned',
            'salary_advance.salary_verify.assigned',
            'salary_advance.outstanding_advance_verify.assigned',
            'salary_advance.threshold_verify.assigned',
            'salary_advance.finance_certify.assigned',
            'salary_advance.payroll_deduction.record.assigned',
        ],
        'inherits' => [],
        'legacy_roles' => ['Finance Controller'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Director Finance and Corporate Services' => [
        'purpose' => 'Assigned financial and corporate approvals',
        'risk_level' => 'critical',
        'permissions' => ['programme.funds_procurement_rates.authorise.assigned', 'salary_advance.approve.assigned', 'travel.request.approve.assigned', 'procurement.purchase_order.create.assigned'],
        'inherits' => ['Finance Officer'],
        // Finance Controller is deliberately mapped to Finance Officer. The
        // director-level approval role is assigned explicitly as its own
        // canonical role and must not be inherited by every controller.
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Programme Officer' => [
        'purpose' => 'Prepare and manage assigned programmes and PIFs',
        'risk_level' => 'medium',
        'permissions' => ['dashboard.view', 'programme.module.view', 'programme.request.create', 'programme.request.read.created', 'programme.request.edit.created', 'programme.request.submit.created', 'programme.document.manage.created', 'programme.conflict_declaration.submit.created', 'programme.mande_link.read.authorised'],
        'inherits' => [],
        // Generic staff must not receive programme-authoring access merely
        // because Programme Officer used to share the staff alias.
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Programme Manager' => [
        'purpose' => 'Programme supervision and assigned programme approvals',
        'risk_level' => 'high',
        'permissions' => ['programme.request.read.assigned', 'programme.manager_review.act.assigned', 'programme.activity_authorise.act.assigned'],
        'inherits' => ['Programme Officer'],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'M&E Officer' => [
        'purpose' => 'Indicator, evidence and activity-report processing',
        'risk_level' => 'medium',
        'permissions' => ['dashboard.view', 'mande.module.view', 'mande.indicator.read', 'mande.indicator.create', 'mande.activity_report.create', 'mande.evidence.upload', 'mande.dashboard.view'],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'M&E Manager' => [
        'purpose' => 'M&E review, acceptance, closure and reporting',
        'risk_level' => 'high',
        'permissions' => ['mande.activity_report.review.assigned', 'mande.activity_report.accept.assigned', 'mande.evidence.validate.assigned', 'mande.configuration.manage', 'mande.strategic_plan.manage'],
        'inherits' => ['M&E Officer'],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Procurement Officer' => [
        'purpose' => 'Procurement administration and controlled process execution',
        'risk_level' => 'high',
        'permissions' => ['dashboard.view', 'procurement.module.view', 'procurement.request.create', 'procurement.request.read.created', 'procurement.request.read.assigned', 'procurement.request.edit.created', 'procurement.request.submit.created', 'procurement.request.review.assigned', 'procurement.rfq.publish.assigned', 'procurement.supplier.read', 'procurement.supplier.approve', 'procurement.purchase_order.create.assigned', 'procurement.report.view'],
        'inherits' => [],
        'legacy_roles' => ['Procurement Officer'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Procurement Evaluation Committee Member' => [
        'purpose' => 'Assigned evaluation only (feature-only)',
        'risk_level' => 'high',
        'permissions' => ['my_work.view', 'procurement.evaluation.read.assigned', 'procurement.evaluation.score.assigned', 'procurement.evaluation.submit.assigned'],
        'inherits' => [],
        'legacy_roles' => ['Committee Member'],
        'feature_only' => true,
        'read_only' => false,
        'no_business_approve' => false,
    ],
    'Internal Auditor' => [
        'purpose' => 'Operate Internal Audit workpapers while remaining read-only on business records',
        'risk_level' => 'high',
        'permissions' => [
            'dashboard.view',
            'audit.event.read.organisation',
            'audit.universe.manage',
            'audit.plan.manage',
            'audit.engagement.manage',
            'audit.engagement.fieldwork',
            'audit.findings.issue',
            'audit.findings.view',
            'audit.workpapers.manage',
            'audit.workpapers.review',
            'audit.report.draft',
            'audit.report.issue',
            'audit.corrective.verify',
            'audit.dashboard.auditor',
            'audit.settings.view',
            'audit.events.view',
            'audit.confidential.view',
            'leave.report.view',
            'procurement.report.view',
            'programme.report.view',
            'salary_advance.report.view',
            'reports.view.authorised',
            'risk.module.view',
            'mande.module.view',
        ],
        'inherits' => [],
        'legacy_roles' => ['Internal Auditor'],
        'feature_only' => false,
        'read_only' => true,
        'no_business_approve' => false,
    ],
    'External Auditor' => [
        'purpose' => 'Time-limited, engagement-scoped read-only assurance access',
        'risk_level' => 'high',
        'permissions' => ['dashboard.view', 'audit.event.read.organisation', 'reports.view.authorised', 'finance.view', 'risk.module.view', 'mande.module.view'],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => true,
        'no_business_approve' => true,
    ],
    'ICT Platform Administrator' => [
        'purpose' => 'Technical platform administration without automatic business-data access',
        'risk_level' => 'critical',
        'permissions' => ['admin.platform.manage', 'admin.users.view', 'admin.users.create', 'admin.users.edit', 'dashboard.view', 'notifications.view.own', 'profile.read.self'],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => true,
    ],
    'Security and Access Administrator' => [
        'purpose' => 'Role and access administration without business approval authority',
        'risk_level' => 'critical',
        'permissions' => ['dashboard.view', 'admin.roles.view', 'admin.roles.manage', 'admin.roles.assign', 'admin.access.simulate', 'admin.access.explore', 'admin.access.requests.manage', 'admin.access.reviews.manage', 'admin.security.manage', 'admin.users.view'],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => true,
    ],
    'Workflow Administrator' => [
        'purpose' => 'Workflow configuration and operational correction under controlled conditions',
        'risk_level' => 'high',
        'permissions' => ['dashboard.view', 'admin.workflow.configure', 'approvals.inbox.view'],
        'inherits' => [],
        'legacy_roles' => [],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => true,
    ],
    'External Supplier' => [
        'purpose' => 'Supplier portal and own procurement interactions',
        'risk_level' => 'medium',
        'permissions' => ['procurement.bid.submit.own', 'procurement.bid.read.own'],
        'inherits' => [],
        'legacy_roles' => ['Supplier', 'Supplier Finance User'],
        'feature_only' => false,
        'read_only' => false,
        'no_business_approve' => false,
    ],
];
