<?php

/** Canonical permission registry — generated from PRD §13 catalogues. */
return [
    'admin.access.explore' => [
        'display_name' => 'Permission explorer',
        'description' => 'Explore who has permissions',
        'module' => 'admin',
        'feature' => 'access',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/access/explorer'],
        'linked_endpoints' => [
            'GET /api/v1/admin/access/coverage',
            'GET /api/v1/admin/access/explore',
        ],
    ],
    'admin.access.requests.manage' => [
        'display_name' => 'Manage access requests',
        'description' => 'Manage access request workflow',
        'module' => 'admin',
        'feature' => 'access',
        'action' => 'manage',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/access/requests'],
        'linked_endpoints' => [
            'GET /api/v1/admin/access/requests',
            'POST /api/v1/admin/access/requests',
            'POST /api/v1/admin/access/requests/{accessRequest}/decide',
        ],
    ],
    'admin.access.reviews.manage' => [
        'display_name' => 'Manage access reviews',
        'description' => 'Manage periodic access reviews',
        'module' => 'admin',
        'feature' => 'access',
        'action' => 'manage',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/access/reviews'],
        'linked_endpoints' => [
            'GET /api/v1/admin/access/reviews',
            'POST /api/v1/admin/access/reviews',
            'POST /api/v1/admin/access/reviews/items/{item}/decide',
        ],
    ],
    'admin.access.simulate' => [
        'display_name' => 'Access simulator',
        'description' => 'Simulate user access without impersonation',
        'module' => 'admin',
        'feature' => 'access',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/access/simulator'],
        'linked_endpoints' => [
            'POST /api/v1/admin/access/users/{user}/simulate',
        ],
    ],
    'admin.organisation.manage' => [
        'display_name' => 'Organisation administration',
        'description' => 'Manage org structure',
        'module' => 'admin',
        'feature' => 'organisation',
        'action' => 'manage',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'admin.platform.manage' => [
        'display_name' => 'Platform administration',
        'description' => 'Technical platform administration',
        'module' => 'admin',
        'feature' => 'platform',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin'],
        'linked_endpoints' => [],
    ],
    'admin-console.view' => [
        'display_name' => 'View Admin Console',
        'description' => 'Open the controlled platform administration dashboard.',
        'module' => 'admin-console',
        'feature' => 'dashboard',
        'action' => 'view',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin'],
        'linked_endpoints' => ['GET /api/v1/admin/dashboard'],
    ],
    'admin-console.view-health' => [
        'display_name' => 'View platform health',
        'description' => 'View platform status, service health, queues, and backup status.',
        'module' => 'admin-console',
        'feature' => 'operations',
        'action' => 'view',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'GET /api/v1/admin/platform-status',
            'GET /api/v1/admin/system-health',
            'GET /api/v1/admin/queues',
            'GET /api/v1/admin/backups',
        ],
    ],
    'admin-console.view-modules' => [
        'display_name' => 'View module registry',
        'description' => 'View active Nexus modules, ownership, dependencies, and status.',
        'module' => 'admin-console',
        'feature' => 'modules',
        'action' => 'view',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'GET /api/v1/admin/modules',
            'GET /api/v1/admin/modules/{id}',
        ],
    ],
    'admin-console.manage-modules' => [
        'display_name' => 'Manage module status',
        'description' => 'Change module availability through controlled status transitions.',
        'module' => 'admin-console',
        'feature' => 'modules',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/modules/{id}/change-status'],
    ],
    'admin-console.view-config' => [
        'display_name' => 'View configuration registry',
        'description' => 'View configuration definitions, active versions, and pending changes.',
        'module' => 'admin-console',
        'feature' => 'configuration',
        'action' => 'view',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['GET /api/v1/admin/configurations'],
    ],
    'admin-console.propose-config' => [
        'display_name' => 'Propose configuration change',
        'description' => 'Create justified, effective-dated configuration change requests.',
        'module' => 'admin-console',
        'feature' => 'configuration',
        'action' => 'create',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/configurations/{id}/change-requests'],
    ],
    'admin-console.review-config' => [
        'display_name' => 'Review configuration change',
        'description' => 'Validate and review proposed configuration changes.',
        'module' => 'admin-console',
        'feature' => 'configuration',
        'action' => 'review',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'POST /api/v1/admin/configuration-changes/{id}/validate',
            'POST /api/v1/admin/configuration-changes/{id}/review',
        ],
    ],
    'admin-console.approve-config' => [
        'display_name' => 'Approve configuration change',
        'description' => 'Approve configuration changes subject to four-eyes controls.',
        'module' => 'admin-console',
        'feature' => 'configuration',
        'action' => 'approve',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/configuration-changes/{id}/approve'],
    ],
    'admin-console.activate-config' => [
        'display_name' => 'Activate configuration',
        'description' => 'Schedule and activate approved configuration versions.',
        'module' => 'admin-console',
        'feature' => 'configuration',
        'action' => 'publish',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'POST /api/v1/admin/configuration-changes/{id}/schedule',
            'POST /api/v1/admin/configuration-changes/{id}/activate',
        ],
    ],
    'admin-console.rollback-config' => [
        'display_name' => 'Rollback configuration',
        'description' => 'Rollback supported configuration to a prior version with reason and audit.',
        'module' => 'admin-console',
        'feature' => 'configuration',
        'action' => 'restore',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/configuration-changes/{id}/rollback'],
    ],
    'admin-console.manage-reference-data' => [
        'display_name' => 'Manage reference data',
        'description' => 'Manage controlled multilingual reference-data sets and items.',
        'module' => 'admin-console',
        'feature' => 'reference-data',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'GET /api/v1/admin/reference-data',
            'POST /api/v1/admin/reference-data/{set}/items',
            'PUT /api/v1/admin/reference-data/items/{id}',
            'POST /api/v1/admin/reference-data/{set}/import',
        ],
    ],
    'admin-console.approve-reference-data' => [
        'display_name' => 'Approve reference-data retirement',
        'description' => 'Deprecate or replace used reference-data items without hard deletion.',
        'module' => 'admin-console',
        'feature' => 'reference-data',
        'action' => 'approve',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/reference-data/items/{id}/deprecate'],
    ],
    'admin-console.manage-feature-flags' => [
        'display_name' => 'Manage feature flags',
        'description' => 'Create, target, activate, and disable governed feature flags.',
        'module' => 'admin-console',
        'feature' => 'feature-flags',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'GET /api/v1/admin/feature-flags',
            'POST /api/v1/admin/feature-flags',
            'POST /api/v1/admin/feature-flags/{id}/activate',
            'POST /api/v1/admin/feature-flags/{id}/disable',
        ],
    ],
    'admin-console.approve-feature-flags' => [
        'display_name' => 'Approve feature flags',
        'description' => 'Approve governed feature flags before activation.',
        'module' => 'admin-console',
        'feature' => 'feature-flags',
        'action' => 'approve',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/feature-flags/{id}/approve'],
    ],
    'admin-console.manage-calendars' => [
        'display_name' => 'Manage calendars',
        'description' => 'Manage institutional calendars, holidays, and closures.',
        'module' => 'admin-console',
        'feature' => 'calendars',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['GET /api/v1/admin/calendars'],
    ],
    'admin-console.manage-numbering' => [
        'display_name' => 'Manage numbering schemes',
        'description' => 'Manage controlled server-side numbering schemes and sequences.',
        'module' => 'admin-console',
        'feature' => 'numbering',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['GET /api/v1/admin/numbering-schemes'],
    ],
    'admin-console.manage-localisation' => [
        'display_name' => 'Manage localisation',
        'description' => 'Manage localisation keys and EN/FR/PT translation status.',
        'module' => 'admin-console',
        'feature' => 'localisation',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['GET /api/v1/admin/localisation'],
    ],
    'admin-console.manage-integrations' => [
        'display_name' => 'Manage integrations',
        'description' => 'Manage integration registry and health without exposing secrets.',
        'module' => 'admin-console',
        'feature' => 'integrations',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['GET /api/v1/admin/integrations'],
    ],
    'admin-console.view-jobs' => [
        'display_name' => 'View jobs and queues',
        'description' => 'View scheduled jobs, queue health, and run history.',
        'module' => 'admin-console',
        'feature' => 'operations',
        'action' => 'view',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'GET /api/v1/admin/jobs',
            'GET /api/v1/admin/job-runs',
            'GET /api/v1/admin/queues',
        ],
    ],
    'admin-console.run-jobs' => [
        'display_name' => 'Run scheduled jobs',
        'description' => 'Manually run authorised jobs with reason, scope, and idempotency controls.',
        'module' => 'admin-console',
        'feature' => 'jobs',
        'action' => 'execute',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/jobs/{id}/run'],
    ],
    'admin-console.manage-dead-letters' => [
        'display_name' => 'Manage dead letters',
        'description' => 'Resolve and replay safe dead-letter records while preserving original payloads.',
        'module' => 'admin-console',
        'feature' => 'queues',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'GET /api/v1/admin/dead-letters',
            'POST /api/v1/admin/dead-letters/{id}/replay',
            'POST /api/v1/admin/dead-letters/{id}/resolve',
        ],
    ],
    'admin-console.manage-maintenance' => [
        'display_name' => 'Manage maintenance',
        'description' => 'Schedule, approve, start, and complete maintenance windows.',
        'module' => 'admin-console',
        'feature' => 'maintenance',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'POST /api/v1/admin/maintenance-windows',
            'POST /api/v1/admin/maintenance-windows/{id}/approve',
            'POST /api/v1/admin/maintenance-windows/{id}/start',
            'POST /api/v1/admin/maintenance-windows/{id}/complete',
        ],
    ],
    'admin-console.manage-banners' => [
        'display_name' => 'Manage system banners',
        'description' => 'Publish controlled user-facing system notices.',
        'module' => 'admin-console',
        'feature' => 'notices',
        'action' => 'publish',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/system-banners'],
    ],
    'admin-console.manage-data-quality' => [
        'display_name' => 'Manage data quality',
        'description' => 'View data quality issues, imports, and migration registers.',
        'module' => 'admin-console',
        'feature' => 'data-quality',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'GET /api/v1/admin/data-quality/issues',
            'GET /api/v1/admin/imports',
            'GET /api/v1/admin/migrations',
        ],
    ],
    'admin-console.request-data-correction' => [
        'display_name' => 'Request data correction',
        'description' => 'Request controlled technical data correction without arbitrary database editing.',
        'module' => 'admin-console',
        'feature' => 'data-corrections',
        'action' => 'create',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/data-corrections'],
    ],
    'admin-console.approve-data-correction' => [
        'display_name' => 'Approve data correction',
        'description' => 'Independently approve controlled data corrections.',
        'module' => 'admin-console',
        'feature' => 'data-corrections',
        'action' => 'approve',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/data-corrections/{id}/approve'],
    ],
    'admin-console.execute-data-correction' => [
        'display_name' => 'Execute data correction',
        'description' => 'Record controlled technical data correction execution and verification.',
        'module' => 'admin-console',
        'feature' => 'data-corrections',
        'action' => 'execute',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/data-corrections/{id}/execute'],
    ],
    'admin-console.view-backups' => [
        'display_name' => 'View backup status',
        'description' => 'View backup, verification, restore-test, and recovery-point status.',
        'module' => 'admin-console',
        'feature' => 'backup-recovery',
        'action' => 'view',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['GET /api/v1/admin/backups'],
    ],
    'admin-console.request-restore' => [
        'display_name' => 'Request restore',
        'description' => 'Request controlled restoration activities without direct backup access.',
        'module' => 'admin-console',
        'feature' => 'backup-recovery',
        'action' => 'create',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/restore-requests'],
    ],
    'admin-console.view-restore' => [
        'display_name' => 'View restore requests',
        'description' => 'View controlled backup and recovery requests.',
        'module' => 'admin-console',
        'feature' => 'backup-recovery',
        'action' => 'view',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['GET /api/v1/admin/restore-requests'],
    ],
    'admin-console.approve-restore' => [
        'display_name' => 'Approve restore requests',
        'description' => 'Approve controlled recovery requests independently of the requester.',
        'module' => 'admin-console',
        'feature' => 'backup-recovery',
        'action' => 'approve',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/restore-requests/{id}/approve'],
    ],
    'admin-console.execute-restore' => [
        'display_name' => 'Execute restore request',
        'description' => 'Record execution and verification of an approved recovery procedure.',
        'module' => 'admin-console',
        'feature' => 'backup-recovery',
        'action' => 'execute',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => ['POST /api/v1/admin/restore-requests/{id}/execute'],
    ],
    'admin-console.manage-support-sessions' => [
        'display_name' => 'Manage support sessions',
        'description' => 'Create, approve, and close scoped support-access sessions.',
        'module' => 'admin-console',
        'feature' => 'support-access',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'POST /api/v1/admin/support-sessions',
            'POST /api/v1/admin/support-sessions/{id}/approve',
            'POST /api/v1/admin/support-sessions/{id}/close',
        ],
    ],
    'admin-console.request-break-glass' => [
        'display_name' => 'Request break-glass access',
        'description' => 'Request emergency access with incident reason and automatic expiry.',
        'module' => 'admin-console',
        'feature' => 'break-glass',
        'action' => 'create',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'POST /api/v1/admin/break-glass',
            'POST /api/v1/admin/break-glass/{id}/close',
        ],
    ],
    'admin-console.approve-break-glass' => [
        'display_name' => 'Approve break-glass access',
        'description' => 'Approve emergency access independently from the requester.',
        'module' => 'admin-console',
        'feature' => 'break-glass',
        'action' => 'approve',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [
            'POST /api/v1/admin/break-glass/{id}/approve',
            'POST /api/v1/admin/break-glass/{id}/close',
        ],
    ],
    'admin-console.view-admin-audit' => [
        'display_name' => 'View administrative audit history',
        'description' => 'View audit evidence for administrative actions.',
        'module' => 'admin-console',
        'feature' => 'audit-history',
        'action' => 'view',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [],
    ],
    'admin-console.export' => [
        'display_name' => 'Export administrative reports',
        'description' => 'Export permission-controlled administrative and operational reports.',
        'module' => 'admin-console',
        'feature' => 'reports',
        'action' => 'export',
        'supported_scopes' => ['system'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/operations'],
        'linked_endpoints' => [],
    ],
    'admin.roles.approve' => [
        'display_name' => 'Approve role assignments',
        'description' => 'Approve role assignments',
        'module' => 'admin',
        'feature' => 'roles',
        'action' => 'approve',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [
            'POST /api/v1/admin/access/grants/{grant}/approve',
            'POST /api/v1/admin/access/grants/{grant}/reject',
            'POST /api/v1/admin/access/role-assignments/{assignment}/approve',
            'POST /api/v1/admin/access/requests/{accessRequest}/decide',
        ],
    ],
    'admin.roles.assign' => [
        'display_name' => 'Assign roles',
        'description' => 'Assign roles to users',
        'module' => 'admin',
        'feature' => 'roles',
        'action' => 'assign',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [
            'POST /api/v1/admin/access/users/{user}/grants',
            'POST /api/v1/admin/access/users/{user}/role-versions/{version}',
        ],
    ],
    'admin.roles.manage' => [
        'display_name' => 'Manage roles',
        'description' => 'Manage role builder',
        'module' => 'admin',
        'feature' => 'roles',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [
            'POST /api/v1/admin/access/roles',
            'POST /api/v1/admin/access/roles/{catalogue}/publish',
            'POST /api/v1/admin/access/users/{user}/denials',
        ],
    ],
    'admin.roles.revoke' => [
        'display_name' => 'Revoke roles',
        'description' => 'Revoke role assignments',
        'module' => 'admin',
        'feature' => 'roles',
        'action' => 'revoke',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [
            'POST /api/v1/admin/access/cutover/revoke-obsolete',
        ],
    ],
    'admin.roles.view' => [
        'display_name' => 'View roles',
        'description' => 'View role catalogue',
        'module' => 'admin',
        'feature' => 'roles',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => ['/admin/roles', '/admin/access'],
        'linked_endpoints' => [
            'GET /api/v1/admin/access/registry',
            'GET /api/v1/admin/access/roles',
            'GET /api/v1/admin/access/users/{user}/profile',
            'GET /api/v1/admin/access/cutover',
        ],
    ],
    'admin.security.manage' => [
        'display_name' => 'Security administration',
        'description' => 'Security and access administration',
        'module' => 'admin',
        'feature' => 'security',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [
            'GET /api/v1/admin/access/governance',
            'PUT /api/v1/admin/access/governance/{decision}',
        ],
    ],
    'admin.users.create' => [
        'display_name' => 'Create users',
        'description' => 'Create users',
        'module' => 'admin',
        'feature' => 'users',
        'action' => 'create',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'admin.users.edit' => [
        'display_name' => 'Edit users',
        'description' => 'Edit users',
        'module' => 'admin',
        'feature' => 'users',
        'action' => 'edit',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'admin.users.view' => [
        'display_name' => 'View users',
        'description' => 'View user admin',
        'module' => 'admin',
        'feature' => 'users',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/admin/users'],
        'linked_endpoints' => [],
    ],
    'admin.workflow.configure' => [
        'display_name' => 'Workflow administration',
        'description' => 'Configure workflows',
        'module' => 'admin',
        'feature' => 'workflow',
        'action' => 'configure',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'approvals.inbox.view' => [
        'display_name' => 'View approvals inbox',
        'description' => 'View workflow approvals inbox',
        'module' => 'approvals',
        'feature' => 'inbox',
        'action' => 'view',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/approvals', '/approvals/inbox'],
        'linked_endpoints' => [],
    ],
    'approvals.task.act.assigned' => [
        'display_name' => 'Act on approval task',
        'description' => 'Act on assigned approval',
        'module' => 'approvals',
        'feature' => 'task',
        'action' => 'approve',
        'supported_scopes' => ['assigned', 'workflow_stage'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'assignment.create' => [
        'display_name' => 'Create assignment',
        'description' => 'Create assignment',
        'module' => 'assignments',
        'feature' => 'assignment',
        'action' => 'create',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'assignment.module.view' => [
        'display_name' => 'View assignments',
        'description' => 'Open assignments',
        'module' => 'assignments',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['self', 'assigned'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/assignments'],
        'linked_endpoints' => [],
    ],
    'assignment.read.assigned' => [
        'display_name' => 'Read assigned assignment',
        'description' => 'Read assigned assignment',
        'module' => 'assignments',
        'feature' => 'assignment',
        'action' => 'read',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'audit.event.read.organisation' => [
        'display_name' => 'Read audit events',
        'description' => 'Read platform audit trail',
        'module' => 'audit',
        'feature' => 'event',
        'action' => 'read',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'audit.export.create.organisation' => [
        'display_name' => 'Export audit',
        'description' => 'Export audit trail',
        'module' => 'audit',
        'feature' => 'export',
        'action' => 'export',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'correspondence.attachment.download' => [
        'display_name' => 'Download correspondence attachment',
        'description' => 'Download attachments',
        'module' => 'correspondence',
        'feature' => 'attachment',
        'action' => 'download',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'correspondence.incoming.register' => [
        'display_name' => 'Register incoming',
        'description' => 'Register incoming correspondence',
        'module' => 'correspondence',
        'feature' => 'registry',
        'action' => 'create',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Confidential',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'correspondence.module.view' => [
        'display_name' => 'View correspondence',
        'description' => 'Open correspondence',
        'module' => 'correspondence',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['department'],
        'risk_level' => 'medium',
        'data_classification' => 'Confidential',
        'mfa_required' => false,
        'linked_routes' => ['/correspondence'],
        'linked_endpoints' => [],
    ],
    'correspondence.read.assigned' => [
        'display_name' => 'Read assigned correspondence',
        'description' => 'Read assigned correspondence',
        'module' => 'correspondence',
        'feature' => 'record',
        'action' => 'read',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Confidential',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'correspondence.read.confidential' => [
        'display_name' => 'Read confidential correspondence',
        'description' => 'Read confidential correspondence',
        'module' => 'correspondence',
        'feature' => 'record',
        'action' => 'read',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'dashboard.view' => [
        'display_name' => 'View dashboard',
        'description' => 'Access personal dashboard',
        'module' => 'dashboard',
        'feature' => 'home',
        'action' => 'view',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'documents.download.authorised' => [
        'display_name' => 'Download documents',
        'description' => 'Download authorised documents',
        'module' => 'documents',
        'feature' => 'document',
        'action' => 'download',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Confidential',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'documents.upload' => [
        'display_name' => 'Upload documents',
        'description' => 'Upload documents',
        'module' => 'documents',
        'feature' => 'document',
        'action' => 'upload',
        'supported_scopes' => ['self', 'created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'documents.view.authorised' => [
        'display_name' => 'View documents',
        'description' => 'View authorised documents',
        'module' => 'documents',
        'feature' => 'document',
        'action' => 'view',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.balance.adjust' => [
        'display_name' => 'Adjust balances',
        'description' => 'Manually adjust leave balances',
        'module' => 'leave',
        'feature' => 'balance',
        'action' => 'edit',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.balance.certify.assigned' => [
        'display_name' => 'Certify balances',
        'description' => 'Certify leave balances',
        'module' => 'leave',
        'feature' => 'balance',
        'action' => 'certify',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.balance.export' => [
        'display_name' => 'Export balances',
        'description' => 'Export leave balances',
        'module' => 'leave',
        'feature' => 'balance',
        'action' => 'export',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.balance.import' => [
        'display_name' => 'Import balances',
        'description' => 'Import leave balances',
        'module' => 'leave',
        'feature' => 'balance',
        'action' => 'import',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.balance.read.assigned_staff' => [
        'display_name' => 'Read staff balances',
        'description' => 'View assigned staff balances',
        'module' => 'leave',
        'feature' => 'balance',
        'action' => 'read',
        'supported_scopes' => ['assigned', 'department'],
        'risk_level' => 'medium',
        'data_classification' => 'Confidential',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.balance.read.self' => [
        'display_name' => 'Read own balance',
        'description' => 'View own leave balances',
        'module' => 'leave',
        'feature' => 'balance',
        'action' => 'read',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.calendar.view.department' => [
        'display_name' => 'Dept leave calendar',
        'description' => 'View department leave calendar',
        'module' => 'leave',
        'feature' => 'calendar',
        'action' => 'view',
        'supported_scopes' => ['department'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.calendar.view.organisation' => [
        'display_name' => 'Org leave calendar',
        'description' => 'View organisation leave calendar',
        'module' => 'leave',
        'feature' => 'calendar',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.module.view' => [
        'display_name' => 'View Leave module',
        'description' => 'Open leave landing',
        'module' => 'leave',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/leave'],
        'linked_endpoints' => [],
    ],
    'leave.report.export' => [
        'display_name' => 'Export leave reports',
        'description' => 'Export leave reports',
        'module' => 'leave',
        'feature' => 'report',
        'action' => 'export',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.report.view' => [
        'display_name' => 'View leave reports',
        'description' => 'View leave reports',
        'module' => 'leave',
        'feature' => 'report',
        'action' => 'view',
        'supported_scopes' => ['department', 'organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.request.authorise.assigned' => [
        'display_name' => 'Authorise leave',
        'description' => 'Final authorise assigned leave',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'approve',
        'supported_scopes' => ['assigned', 'workflow_stage'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.request.cancel.created' => [
        'display_name' => 'Cancel leave',
        'description' => 'Cancel own leave',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'cancel',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.request.create.self' => [
        'display_name' => 'Create own leave',
        'description' => 'Create leave for self',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'create',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/leave/create'],
        'linked_endpoints' => ['POST /api/v1/leave/requests'],
    ],
    'leave.request.edit.created' => [
        'display_name' => 'Edit created leave',
        'description' => 'Edit draft leave created by actor',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'edit',
        'supported_scopes' => ['created'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.request.read.direct_reports' => [
        'display_name' => 'Read direct reports leave',
        'description' => 'View leave for direct reports',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'read',
        'supported_scopes' => ['direct_reports', 'department'],
        'risk_level' => 'medium',
        'data_classification' => 'Confidential',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.request.read.self' => [
        'display_name' => 'Read own leave',
        'description' => 'View own leave requests',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'read',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/leave'],
        'linked_endpoints' => ['GET /api/v1/leave/requests'],
    ],
    'leave.request.recommend.assigned' => [
        'display_name' => 'Recommend leave',
        'description' => 'Recommend assigned leave',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'recommend',
        'supported_scopes' => ['assigned', 'direct_reports'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.request.reject.assigned' => [
        'display_name' => 'Reject leave',
        'description' => 'Reject assigned leave',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'reject',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.request.return.assigned' => [
        'display_name' => 'Return leave',
        'description' => 'Return leave for correction',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'return',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.request.submit.created' => [
        'display_name' => 'Submit leave',
        'description' => 'Submit own leave request',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'submit',
        'supported_scopes' => ['created'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.request.withdraw.created' => [
        'display_name' => 'Withdraw leave',
        'description' => 'Withdraw own leave',
        'module' => 'leave',
        'feature' => 'request',
        'action' => 'withdraw',
        'supported_scopes' => ['created'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.type.configure' => [
        'display_name' => 'Configure leave types',
        'description' => 'Configure leave types/policies',
        'module' => 'leave',
        'feature' => 'config',
        'action' => 'configure',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'leave.workflow.configure' => [
        'display_name' => 'Configure leave workflow',
        'description' => 'Configure leave workflow',
        'module' => 'leave',
        'feature' => 'config',
        'action' => 'configure',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.activity_report.accept.assigned' => [
        'display_name' => 'Accept activity report',
        'description' => 'Accept assigned report',
        'module' => 'mande',
        'feature' => 'activity_report',
        'action' => 'approve',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.activity_report.create' => [
        'display_name' => 'Create activity report',
        'description' => 'Create activity report',
        'module' => 'mande',
        'feature' => 'activity_report',
        'action' => 'create',
        'supported_scopes' => ['self', 'created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.activity_report.review.assigned' => [
        'display_name' => 'Review activity report',
        'description' => 'Review assigned report',
        'module' => 'mande',
        'feature' => 'activity_report',
        'action' => 'review',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.configuration.manage' => [
        'display_name' => 'Configure M&E',
        'description' => 'Configure M&E',
        'module' => 'mande',
        'feature' => 'config',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.dashboard.view' => [
        'display_name' => 'View M&E dashboard',
        'description' => 'View M&E dashboard',
        'module' => 'mande',
        'feature' => 'dashboard',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.evidence.upload' => [
        'display_name' => 'Upload evidence',
        'description' => 'Upload M&E evidence',
        'module' => 'mande',
        'feature' => 'evidence',
        'action' => 'upload',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.evidence.validate.assigned' => [
        'display_name' => 'Validate evidence',
        'description' => 'Validate evidence',
        'module' => 'mande',
        'feature' => 'evidence',
        'action' => 'verify',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.indicator.create' => [
        'display_name' => 'Create indicators',
        'description' => 'Create indicators',
        'module' => 'mande',
        'feature' => 'indicator',
        'action' => 'create',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.indicator.read' => [
        'display_name' => 'Read indicators',
        'description' => 'Read indicators',
        'module' => 'mande',
        'feature' => 'indicator',
        'action' => 'read',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'mande.module.view' => [
        'display_name' => 'View M&E',
        'description' => 'Open M&E module',
        'module' => 'mande',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/mande'],
        'linked_endpoints' => [],
    ],
    'mande.strategic_plan.manage' => [
        'display_name' => 'Manage strategic plan',
        'description' => 'Manage strategic plan',
        'module' => 'mande',
        'feature' => 'strategic_plan',
        'action' => 'manage',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'my_work.tasks.read.assigned' => [
        'display_name' => 'Read assigned tasks',
        'description' => 'See assigned tasks in My Work',
        'module' => 'dashboard',
        'feature' => 'my_work',
        'action' => 'read',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'my_work.view' => [
        'display_name' => 'View My Work',
        'description' => 'Access My Work hub',
        'module' => 'dashboard',
        'feature' => 'my_work',
        'action' => 'view',
        'supported_scopes' => ['self', 'assigned'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/my-work'],
        'linked_endpoints' => [],
    ],
    'notifications.manage.preferences' => [
        'display_name' => 'Manage notification preferences',
        'description' => 'Manage own preferences',
        'module' => 'notifications',
        'feature' => 'preferences',
        'action' => 'manage',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'notifications.view.own' => [
        'display_name' => 'View own notifications',
        'description' => 'View own notifications',
        'module' => 'notifications',
        'feature' => 'notification',
        'action' => 'view',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/notifications'],
        'linked_endpoints' => [],
    ],
    'procurement.award.approve.assigned' => [
        'display_name' => 'Approve award',
        'description' => 'Approve award',
        'module' => 'procurement',
        'feature' => 'award',
        'action' => 'approve',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [
            'POST /api/v1/procurement/tenders/{tender}/award',
            'POST /api/v1/procurement/tenders/{tender}/recommend-award',
        ],
    ],
    'procurement.bid.open.assigned' => [
        'display_name' => 'Open bids',
        'description' => 'Open sealed bids',
        'module' => 'procurement',
        'feature' => 'bid',
        'action' => 'manage',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.configuration.manage' => [
        'display_name' => 'Configure procurement',
        'description' => 'Configure procurement',
        'module' => 'procurement',
        'feature' => 'config',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.evaluation.read.assigned' => [
        'display_name' => 'Read evaluation',
        'description' => 'Read assigned evaluations',
        'module' => 'procurement',
        'feature' => 'evaluation',
        'action' => 'read',
        'supported_scopes' => ['assigned', 'specific_records'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => ['/my-work/procurement-evaluations'],
        'linked_endpoints' => [
            'GET /api/v1/procurement/committee-evaluations',
            'GET /api/v1/procurement/committee-evaluations/{procurementRequest}',
        ],
    ],
    'procurement.evaluation.score.assigned' => [
        'display_name' => 'Score evaluation',
        'description' => 'Score assigned evaluation',
        'module' => 'procurement',
        'feature' => 'evaluation',
        'action' => 'edit',
        'supported_scopes' => ['assigned', 'specific_records'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.evaluation.submit.assigned' => [
        'display_name' => 'Submit evaluation',
        'description' => 'Submit evaluation scores',
        'module' => 'procurement',
        'feature' => 'evaluation',
        'action' => 'submit',
        'supported_scopes' => ['assigned', 'specific_records'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.module.view' => [
        'display_name' => 'View procurement module',
        'description' => 'Open procurement landing',
        'module' => 'procurement',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['self', 'created'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/procurement'],
        'linked_endpoints' => [],
    ],
    'procurement.purchase_order.create.assigned' => [
        'display_name' => 'Create PO',
        'description' => 'Create purchase order',
        'module' => 'procurement',
        'feature' => 'po',
        'action' => 'create',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.report.export' => [
        'display_name' => 'Export procurement reports',
        'description' => 'Export procurement reports',
        'module' => 'procurement',
        'feature' => 'report',
        'action' => 'export',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.report.view' => [
        'display_name' => 'View procurement reports',
        'description' => 'View procurement reports',
        'module' => 'procurement',
        'feature' => 'report',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.request.approve.assigned' => [
        'display_name' => 'Approve procurement',
        'description' => 'Approve assigned procurement',
        'module' => 'procurement',
        'feature' => 'request',
        'action' => 'approve',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.request.create' => [
        'display_name' => 'Create procurement',
        'description' => 'Create procurement request',
        'module' => 'procurement',
        'feature' => 'request',
        'action' => 'create',
        'supported_scopes' => ['self'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/procurement/create'],
        'linked_endpoints' => [],
    ],
    'procurement.request.edit.created' => [
        'display_name' => 'Edit procurement',
        'description' => 'Edit draft procurement',
        'module' => 'procurement',
        'feature' => 'request',
        'action' => 'edit',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.request.read.assigned' => [
        'display_name' => 'Read assigned procurement',
        'description' => 'Read assigned procurements',
        'module' => 'procurement',
        'feature' => 'request',
        'action' => 'read',
        'supported_scopes' => ['assigned', 'specific_records'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.request.read.created' => [
        'display_name' => 'Read created procurement',
        'description' => 'Read own procurements',
        'module' => 'procurement',
        'feature' => 'request',
        'action' => 'read',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.request.review.assigned' => [
        'display_name' => 'Review procurement',
        'description' => 'Review assigned procurement',
        'module' => 'procurement',
        'feature' => 'request',
        'action' => 'review',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.request.submit.created' => [
        'display_name' => 'Submit procurement',
        'description' => 'Submit procurement',
        'module' => 'procurement',
        'feature' => 'request',
        'action' => 'submit',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.rfq.publish.assigned' => [
        'display_name' => 'Publish RFQ',
        'description' => 'Publish RFQ',
        'module' => 'procurement',
        'feature' => 'rfq',
        'action' => 'publish',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.supplier.approve' => [
        'display_name' => 'Approve supplier',
        'description' => 'Approve suppliers',
        'module' => 'procurement',
        'feature' => 'supplier',
        'action' => 'approve',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'procurement.supplier.read' => [
        'display_name' => 'Read suppliers',
        'description' => 'Read supplier records',
        'module' => 'procurement',
        'feature' => 'supplier',
        'action' => 'read',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/procurement/vendors'],
        'linked_endpoints' => [],
    ],
    'profile.edit.self' => [
        'display_name' => 'Edit own profile',
        'description' => 'Edit own profile',
        'module' => 'profiles',
        'feature' => 'profile',
        'action' => 'edit',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'profile.read.self' => [
        'display_name' => 'Read own profile',
        'description' => 'Read own profile',
        'module' => 'profiles',
        'feature' => 'profile',
        'action' => 'read',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.activity_authorise.act.assigned' => [
        'display_name' => 'Authorise activity',
        'description' => 'Authorise programme activity',
        'module' => 'programme',
        'feature' => 'workflow',
        'action' => 'approve',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.arrival_departure.manage.created' => [
        'display_name' => 'Manage arrival/departure',
        'description' => 'Manage arrival departure',
        'module' => 'programme',
        'feature' => 'logistics',
        'action' => 'manage',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.budget_availability.confirm.assigned' => [
        'display_name' => 'Confirm budget availability',
        'description' => 'Confirm budget availability',
        'module' => 'programme',
        'feature' => 'finance',
        'action' => 'certify',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.configuration.manage' => [
        'display_name' => 'Configure programmes',
        'description' => 'Configure programme settings',
        'module' => 'programme',
        'feature' => 'config',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.conflict_declaration.submit.created' => [
        'display_name' => 'Submit conflict declaration',
        'description' => 'Submit conflict declaration',
        'module' => 'programme',
        'feature' => 'compliance',
        'action' => 'submit',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Confidential',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.document.manage.created' => [
        'display_name' => 'Manage PIF documents',
        'description' => 'Manage PIF documents',
        'module' => 'programme',
        'feature' => 'documents',
        'action' => 'manage',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.finance_review.read.assigned' => [
        'display_name' => 'Read finance review',
        'description' => 'Read PIF finance review fields',
        'module' => 'programme',
        'feature' => 'finance',
        'action' => 'read',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.finance_review.update.assigned' => [
        'display_name' => 'Update finance review',
        'description' => 'Update Finance-only PIF fields',
        'module' => 'programme',
        'feature' => 'finance',
        'action' => 'edit',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => ['/pif'],
        'linked_endpoints' => ['PUT /api/v1/programmes/{id}/finance-review'],
    ],
    'programme.funds_procurement_rates.authorise.assigned' => [
        'display_name' => 'Authorise funds/rates',
        'description' => 'Authorise funding procurement rates',
        'module' => 'programme',
        'feature' => 'finance',
        'action' => 'approve',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.manager_review.act.assigned' => [
        'display_name' => 'Manager review PIF',
        'description' => 'Act on manager review',
        'module' => 'programme',
        'feature' => 'workflow',
        'action' => 'review',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.mande_link.read.authorised' => [
        'display_name' => 'Read M&E link',
        'description' => 'Read authorised M&E link status',
        'module' => 'programme',
        'feature' => 'mande',
        'action' => 'read',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.module.view' => [
        'display_name' => 'View PIF module',
        'description' => 'Open programme/PIF surfaces',
        'module' => 'programme',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['self', 'created'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/pif'],
        'linked_endpoints' => [],
    ],
    'programme.preparation.delegate' => [
        'display_name' => 'Delegate preparation',
        'description' => 'Delegate PIF preparation',
        'module' => 'programme',
        'feature' => 'request',
        'action' => 'delegate',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.procurement_item.transfer.assigned' => [
        'display_name' => 'Transfer procurement items',
        'description' => 'Transfer approved PIF items to procurement',
        'module' => 'programme',
        'feature' => 'procurement',
        'action' => 'execute',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.report.export' => [
        'display_name' => 'Export programme reports',
        'description' => 'Export programme reports',
        'module' => 'programme',
        'feature' => 'report',
        'action' => 'export',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.report.view' => [
        'display_name' => 'View programme reports',
        'description' => 'View programme reports',
        'module' => 'programme',
        'feature' => 'report',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.request.create' => [
        'display_name' => 'Create PIF',
        'description' => 'Create programme implementation form',
        'module' => 'programme',
        'feature' => 'request',
        'action' => 'create',
        'supported_scopes' => ['self'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/pif/create'],
        'linked_endpoints' => ['POST /api/v1/programmes'],
    ],
    'programme.request.edit.created' => [
        'display_name' => 'Edit created PIF',
        'description' => 'Edit draft PIF',
        'module' => 'programme',
        'feature' => 'request',
        'action' => 'edit',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.request.read.assigned' => [
        'display_name' => 'Read assigned PIF',
        'description' => 'Read assigned PIFs',
        'module' => 'programme',
        'feature' => 'request',
        'action' => 'read',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.request.read.created' => [
        'display_name' => 'Read created PIF',
        'description' => 'Read PIFs created by actor',
        'module' => 'programme',
        'feature' => 'request',
        'action' => 'read',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.request.submit.created' => [
        'display_name' => 'Submit PIF',
        'description' => 'Submit PIF',
        'module' => 'programme',
        'feature' => 'request',
        'action' => 'submit',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.request.withdraw.created' => [
        'display_name' => 'Withdraw PIF',
        'description' => 'Withdraw PIF',
        'module' => 'programme',
        'feature' => 'request',
        'action' => 'withdraw',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.sg_approval.act.assigned' => [
        'display_name' => 'SG approve PIF',
        'description' => 'SG approval action',
        'module' => 'programme',
        'feature' => 'workflow',
        'action' => 'approve',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'programme.supporting_officer.assign' => [
        'display_name' => 'Assign supporting officer',
        'description' => 'Assign supporting officers',
        'module' => 'programme',
        'feature' => 'staffing',
        'action' => 'assign',
        'supported_scopes' => ['created', 'assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'reports.export.authorised' => [
        'display_name' => 'Export reports',
        'description' => 'Export authorised reports',
        'module' => 'reports',
        'feature' => 'report',
        'action' => 'export',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'reports.schedule' => [
        'display_name' => 'Schedule reports',
        'description' => 'Create permission-aware scheduled management-information reports.',
        'module' => 'reports',
        'feature' => 'schedules',
        'action' => 'create',
        'supported_scopes' => ['self'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/reports'],
        'linked_endpoints' => ['POST /api/v1/reports/schedules'],
    ],
    'reports.manage-schedules' => [
        'display_name' => 'Manage scheduled reports',
        'description' => 'Approve and pause scheduled management-information reports.',
        'module' => 'reports',
        'feature' => 'schedules',
        'action' => 'manage',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'critical',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => ['/reports'],
        'linked_endpoints' => [
            'POST /api/v1/reports/schedules/{id}/approve',
            'POST /api/v1/reports/schedules/{id}/pause',
            'GET /api/v1/reports/export-events/{id}/download',
        ],
    ],
    'reports.view.authorised' => [
        'display_name' => 'View reports',
        'description' => 'View authorised reports',
        'module' => 'reports',
        'feature' => 'report',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/reports'],
        'linked_endpoints' => [],
    ],
    'risk.create' => [
        'display_name' => 'Create risk',
        'description' => 'Create risk',
        'module' => 'risk',
        'feature' => 'risk',
        'action' => 'create',
        'supported_scopes' => ['department'],
        'risk_level' => 'medium',
        'data_classification' => 'Confidential',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'risk.manage' => [
        'display_name' => 'Manage risk',
        'description' => 'Manage risk framework',
        'module' => 'risk',
        'feature' => 'risk',
        'action' => 'manage',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Confidential',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'risk.module.view' => [
        'display_name' => 'View risk register',
        'description' => 'Open risk register',
        'module' => 'risk',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'medium',
        'data_classification' => 'Confidential',
        'mfa_required' => false,
        'linked_routes' => ['/risk'],
        'linked_endpoints' => [],
    ],
    'salary_advance.approve.assigned' => [
        'display_name' => 'Approve salary advance',
        'description' => 'Approve assigned advance',
        'module' => 'salary_advance',
        'feature' => 'workflow',
        'action' => 'approve',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.configuration.manage' => [
        'display_name' => 'Configure salary advances',
        'description' => 'Configure SA policies',
        'module' => 'salary_advance',
        'feature' => 'config',
        'action' => 'manage',
        'supported_scopes' => ['system'],
        'risk_level' => 'critical',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.finance_certify.assigned' => [
        'display_name' => 'Finance certify advance',
        'description' => 'Certify salary advance',
        'module' => 'salary_advance',
        'feature' => 'finance',
        'action' => 'certify',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.financial_details.read.assigned' => [
        'display_name' => 'Read financial details',
        'description' => 'Read salary figures for assigned advances',
        'module' => 'salary_advance',
        'feature' => 'finance',
        'action' => 'read',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Highly Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.module.view' => [
        'display_name' => 'View salary advances',
        'description' => 'Open salary advance module',
        'module' => 'salary_advance',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['self'],
        'risk_level' => 'medium',
        'data_classification' => 'Restricted',
        'mfa_required' => false,
        'linked_routes' => ['/salary-advances'],
        'linked_endpoints' => [],
    ],
    'salary_advance.outstanding_advance_verify.assigned' => [
        'display_name' => 'Verify outstanding',
        'description' => 'Verify outstanding advances',
        'module' => 'salary_advance',
        'feature' => 'finance',
        'action' => 'verify',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.payroll_deduction.record.assigned' => [
        'display_name' => 'Record payroll deduction',
        'description' => 'Record payroll deduction',
        'module' => 'salary_advance',
        'feature' => 'payroll',
        'action' => 'record',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.reject.assigned' => [
        'display_name' => 'Reject salary advance',
        'description' => 'Reject advance',
        'module' => 'salary_advance',
        'feature' => 'workflow',
        'action' => 'reject',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.report.export' => [
        'display_name' => 'Export SA reports',
        'description' => 'Export salary advance reports',
        'module' => 'salary_advance',
        'feature' => 'report',
        'action' => 'export',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'critical',
        'data_classification' => 'Highly Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.report.view' => [
        'display_name' => 'View SA reports',
        'description' => 'View salary advance reports',
        'module' => 'salary_advance',
        'feature' => 'report',
        'action' => 'view',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.request.create.self' => [
        'display_name' => 'Create salary advance',
        'description' => 'Create own salary advance',
        'module' => 'salary_advance',
        'feature' => 'request',
        'action' => 'create',
        'supported_scopes' => ['self'],
        'risk_level' => 'medium',
        'data_classification' => 'Restricted',
        'mfa_required' => false,
        'linked_routes' => ['/salary-advances/create'],
        'linked_endpoints' => [],
    ],
    'salary_advance.request.edit.created' => [
        'display_name' => 'Edit salary advance',
        'description' => 'Edit draft advance',
        'module' => 'salary_advance',
        'feature' => 'request',
        'action' => 'edit',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Restricted',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.request.read.self' => [
        'display_name' => 'Read own salary advance',
        'description' => 'Read own advances',
        'module' => 'salary_advance',
        'feature' => 'request',
        'action' => 'read',
        'supported_scopes' => ['self'],
        'risk_level' => 'medium',
        'data_classification' => 'Restricted',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.request.submit.created' => [
        'display_name' => 'Submit salary advance',
        'description' => 'Submit advance',
        'module' => 'salary_advance',
        'feature' => 'request',
        'action' => 'submit',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Restricted',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.request.withdraw.created' => [
        'display_name' => 'Withdraw salary advance',
        'description' => 'Withdraw advance',
        'module' => 'salary_advance',
        'feature' => 'request',
        'action' => 'withdraw',
        'supported_scopes' => ['created'],
        'risk_level' => 'medium',
        'data_classification' => 'Restricted',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.return.assigned' => [
        'display_name' => 'Return salary advance',
        'description' => 'Return for correction',
        'module' => 'salary_advance',
        'feature' => 'workflow',
        'action' => 'return',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.salary_verify.assigned' => [
        'display_name' => 'Verify salary',
        'description' => 'Verify salary for advance',
        'module' => 'salary_advance',
        'feature' => 'finance',
        'action' => 'verify',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'critical',
        'data_classification' => 'Highly Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.settlement.close.assigned' => [
        'display_name' => 'Close settlement',
        'description' => 'Close advance settlement',
        'module' => 'salary_advance',
        'feature' => 'payroll',
        'action' => 'close',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'salary_advance.threshold_verify.assigned' => [
        'display_name' => 'Verify threshold',
        'description' => 'Verify 50% threshold',
        'module' => 'salary_advance',
        'feature' => 'finance',
        'action' => 'verify',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Restricted',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'signatures.enrol.self' => [
        'display_name' => 'Enrol signature',
        'description' => 'Enrol own signature',
        'module' => 'profiles',
        'feature' => 'signature',
        'action' => 'create',
        'supported_scopes' => ['self'],
        'risk_level' => 'medium',
        'data_classification' => 'Restricted',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'timesheet.approve.assigned' => [
        'display_name' => 'Approve timesheet',
        'description' => 'Approve timesheet',
        'module' => 'timesheets',
        'feature' => 'timesheet',
        'action' => 'approve',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'timesheet.create.self' => [
        'display_name' => 'Create timesheet',
        'description' => 'Create own timesheet',
        'module' => 'timesheets',
        'feature' => 'timesheet',
        'action' => 'create',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'timesheet.module.view' => [
        'display_name' => 'View timesheets',
        'description' => 'Open timesheets',
        'module' => 'timesheets',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/hr/timesheets'],
        'linked_endpoints' => [],
    ],
    'timesheet.read.self' => [
        'display_name' => 'Read own timesheet',
        'description' => 'Read own timesheet',
        'module' => 'timesheets',
        'feature' => 'timesheet',
        'action' => 'read',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'travel.module.view' => [
        'display_name' => 'View travel',
        'description' => 'Open travel module',
        'module' => 'travel',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/travel'],
        'linked_endpoints' => [],
    ],
    'travel.report.export' => [
        'display_name' => 'Export travel reports',
        'description' => 'Export travel reports',
        'module' => 'travel',
        'feature' => 'report',
        'action' => 'export',
        'supported_scopes' => ['organisation'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'travel.request.approve.assigned' => [
        'display_name' => 'Approve travel',
        'description' => 'Approve assigned travel',
        'module' => 'travel',
        'feature' => 'request',
        'action' => 'approve',
        'supported_scopes' => ['assigned'],
        'risk_level' => 'high',
        'data_classification' => 'Internal',
        'mfa_required' => true,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'travel.request.create.self' => [
        'display_name' => 'Create travel',
        'description' => 'Create own travel',
        'module' => 'travel',
        'feature' => 'request',
        'action' => 'create',
        'supported_scopes' => ['self'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'travel.request.read.self' => [
        'display_name' => 'Read own travel',
        'description' => 'Read own travel',
        'module' => 'travel',
        'feature' => 'request',
        'action' => 'read',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'weekly_report.create.self' => [
        'display_name' => 'Create weekly summary',
        'description' => 'Create own weekly summary',
        'module' => 'weekly_reports',
        'feature' => 'report',
        'action' => 'create',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
    'weekly_report.module.view' => [
        'display_name' => 'View weekly summaries',
        'description' => 'Open weekly summaries',
        'module' => 'weekly_reports',
        'feature' => 'module',
        'action' => 'view',
        'supported_scopes' => ['self'],
        'risk_level' => 'low',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => ['/weekly-summaries'],
        'linked_endpoints' => [],
    ],
    'weekly_report.review.team' => [
        'display_name' => 'Review team weekly',
        'description' => 'Review team weekly summaries',
        'module' => 'weekly_reports',
        'feature' => 'report',
        'action' => 'review',
        'supported_scopes' => ['direct_reports', 'department'],
        'risk_level' => 'medium',
        'data_classification' => 'Internal',
        'mfa_required' => false,
        'linked_routes' => [],
        'linked_endpoints' => [],
    ],
];
