// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGjQLxDkXsx_eFXBS08a1lPhyCf71_TE4',
    appId: '1:655712918606:web:f703996b330f241618371f',
    messagingSenderId: '655712918606',
    projectId: 'sadcpfnexus',
    authDomain: 'sadcpfnexus.firebaseapp.com',
    storageBucket: 'sadcpfnexus.firebasestorage.app',
    measurementId: 'G-5NM5J9EB8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFyiydsQWz-EI4qj2tVb15tIE8JBJWok',
    appId: '1:655712918606:android:b1aec16cf20c8c9418371f',
    messagingSenderId: '655712918606',
    projectId: 'sadcpfnexus',
    storageBucket: 'sadcpfnexus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZqVyNAdr8hvkPVTz2yMADAj-9EEJruAA',
    appId: '1:655712918606:ios:fc75e4f054fb450b18371f',
    messagingSenderId: '655712918606',
    projectId: 'sadcpfnexus',
    storageBucket: 'sadcpfnexus.firebasestorage.app',
    iosBundleId: 'org.sadcpf.sadcpfNexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGjQLxDkXsx_eFXBS08a1lPhyCf71_TE4',
    appId: '1:655712918606:web:5bc91979fba02d9318371f',
    messagingSenderId: '655712918606',
    projectId: 'sadcpfnexus',
    authDomain: 'sadcpfnexus.firebaseapp.com',
    storageBucket: 'sadcpfnexus.firebasestorage.app',
    measurementId: 'G-XM1MFW8EGT',
  );
}
